services:
  - type: web
    name: hidop
    runtime: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py

  - type: web
    name: hidop-esp
    runtime: python
    rootDir: esp
    buildCommand: pip install -r requirements.txt
    startCommand: python3 server.py
