services:
  - type: web
    name: hidop
    runtime: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py

  - type: static
    name: hidop-esp
    rootDir: esp
    buildCommand: npm install && npm run build
    staticPublishPath: dist
